[package]
name = "vpp-layout"
description = "Turns styled elements into positioned boxes."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
vpp-dom.workspace = true
vpp-style.workspace = true

[lints]
workspace = true
